resources:
- name: repo
  type: git
  source:
    uri: https://github.com/alejandrofca/concourse-git-resource.git

jobs:
- name: hello-world-job2
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task2
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!!!"]
